Url validation
projecttacoma/bulk-submit-demo pull request #9
Opened 2022-05-18 23:13 UTC by lmd59

## Summary

Add validation of the export URL.

### New Behavior
The export URL must validate as a URL according to javascript URL creation requirements (if we really want a regex instead, there are some comments about regex-ing in the code that can otherwise be removed).
If the string input does not validate as a URL, the input box text is highlighted red and an error message indicates that a "Valid URL is required". Additionally, the URL must be validated to show the request body in the Kickoff Request Panel. A valid URL is automatically populated into the Kickoff Request Body.

### Code Changes

## Testing Guidance

2022-05-19 14:10 UTC, natjoe4 requested changes
This works great! A few small comments. Another thing that might be nice is to disable the `POST` button when the kickoff body is not populated, but if that seems like scope creep, we can easily make another task.

2022-05-19 14:10 UTC, natjoe4 commented on __tests__/components/ExportURLInput.test.tsx
>      expect(textbox.value).toBe('http://localhost:3001/');
Can we add a line here with `expect(textbox).toBeValid();`

2022-05-19 14:10 UTC, natjoe4 commented on __tests__/components/ResetInputsButton.test.tsx
> +    expect(textbox.value).toBe('');
Maybe another line here to check that the textbox isValid after reset?

2022-05-19 14:10 UTC, natjoe4 commented on components/ExportURLInput.tsx
> +  }
I like this method! I would add a check for any characters which invalidate a URL like spaces, or `<, >, {, }` etc...

2022-05-19 14:10 UTC, natjoe4 commented on __tests__/components/ExportURLInput.test.tsx
> +// import KickoffBody from '../../components/KickoffRequestView/KickoffBody'
```suggestion
```

2022-05-19 15:40 UTC, lmd59 commented on __tests__/components/ExportURLInput.test.tsx
>      expect(textbox.value).toBe('http://localhost:3001/');
> This works great! A few small comments. Another thing that might be nice is to disable the `POST` button when the kickoff body is not populated, but if that seems like scope creep, we can easily make another task.

Yeah- I thought about button disabling, but I thought it should probably just match what we were doing already for empty exportURL field. We could certainly make another task for it!

2022-05-19 15:40 UTC, lmd59 commented
> This works great! A few small comments. Another thing that might be nice is to disable the `POST` button when the kickoff body is not populated, but if that seems like scope creep, we can easily make another task.

Yeah- I thought about button disabling, but I thought it should probably just match what we were doing already for empty exportURL field. We could certainly make another task for it!

2022-05-19 15:44 UTC, lmd59 commented on __tests__/components/ExportURLInput.test.tsx
>      expect(textbox.value).toBe('http://localhost:3001/');
Smart add!

2022-05-19 20:01 UTC, natjoe4 commented
Open Question: Is this method of URL validation a suitable replacement for Regex?

2022-05-23 15:48 UTC, sarahmcdougall commented
> Open Question: Is this method of URL validation a suitable replacement for Regex?

I think it's fine - I don't think we need anything super advanced since this app is for demo purposes and not for production. I think this approach catches the main issues we want to address, such as having spaces or invalid characters

2022-05-26 16:13 UTC, natjoe4 approved these changes

2022-05-26 16:14 UTC, merged